spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/user_db

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG
